train:
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
inference:
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
